basic usage vignette
macmillancontentscience/tidybert pull request #5
Opened 2022-08-09 04:17 UTC by jonathanbratt

leaving this as draft PR for now, because I'll need to finish proofreading and make sure the DESCRIPTION is updated, but wanted to run the vignette by you first.

2022-08-09 20:20 UTC, jonthegeek requested changes
Several little things and a couple bigger things. This definitely inspired me to streamline some things in the package!

2022-08-09 20:20 UTC, jonthegeek commented on vignettes/basic_usage.Rmd
> +mean(preds$.pred_class == as.factor(testing_set$target))
```suggestion
mean(preds$.pred_class == testing_set$target)
```
(you already did the as.factor step)

2022-08-10 14:23 UTC, jonathanbratt commented on vignettes/basic_usage.Rmd
> +It is the successor to the TensorFlow-based package {[RBERT](https://github.com/jonathanbratt/RBERT)}.
I agree

2022-08-10 14:25 UTC, jonathanbratt commented on vignettes/basic_usage.Rmd
> +It also enables exploring the output embeddings and attention weights produced by a BERT model, to better understand how these models work.
Once we're ready to link to a package, I'd do this. But with RBERTviz in a footnote for now, I don't feel the need to elaborate further yet.

2022-08-10 14:30 UTC, jonathanbratt commented on vignettes/basic_usage.Rmd
> +## RBERTviz compatibility
yup

2022-08-10 15:01 UTC, jonathanbratt commented on vignettes/basic_usage.Rmd
> +First, let's get some training data...
good call

2022-08-10 17:22 UTC, jonthegeek approved these changes
Looks good!

2022-08-10 17:22 UTC, merged